# Generated by Django 5.2.4 on 2025-07-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='descripcion',
            new_name='creditos',
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.CharField(default='Pop', max_length=50),
            preserve_default=False,
        ),
    ]
