# Generated by Django 5.2.4 on 2025-07-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_rename_descripcion_cancion_creditos_cancion_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
